name: coffeetracker
description: "CoffeeTracker is an application designed to help users track their coffee buying and drinking habits. Recognizing that buying coffee in cafes can be both expensive and addictive, this app aims to provide a seamless and efficient way for users to log their coffee purchases and homemade coffee consumption."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  firebase_core: ^3.1.1
  flutter_dotenv: ^5.1.0
  device_info_plus: ^10.1.0
  cloud_firestore: ^5.0.2
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.2
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.1.41+1
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.3
  csv: ^6.0.0
  provider: ^6.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 26


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/home.png
    - assets/latte.png
    - assets/coffee-cup.png
    - assets/coffee-machine.png
    - assets/money_grey.png
    - assets/favourite.png
